main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about', views.AboutView.as_view(), name='about'),
    path('services', views.ServicesView.as_view(), name='services'),
    path('projects', views.ProjectsView.as_view(), name='projects'),
    path('news', views.NewsView.as_view(), name='news'),
    path('faq', views.FaqView.as_view(), name='faq'),
    path('products', views.ProductsView.as_view(), name='products'),
    path('offer', views.OfferView.as_view(), name='offer'),
    path('contact', views.ContactView.as_view(), name='contact'),
]

ozgreenhouse/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('control/', admin.site.urls),
    path('', include('main.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

class AboutView(TemplateView):
    template_name = 'about.html'

class ServicesView(TemplateView):
    template_name = 'services.html'

class ProjectsView(TemplateView):
    template_name = 'projects.html'

class NewsView(TemplateView):
    template_name = 'news.html'

class FaqView(TemplateView):
    template_name = 'faq.html'

class ProductsView(TemplateView):
    template_name = 'products.html'

class OfferView(TemplateView):
        template_name = 'offer.html'

class ContactView(TemplateView):
     template_name = 'contact.html'

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Page Header Start -->
    <div class="container-fluid page-header py-5 mb-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container text-center py-5">
            <h1 class="display-3 text-white mb-4 animated slideInDown">Bizim haqqımızda</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a href="#">Əsas səhifə</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Bizim haqqımızda</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->
    
    <!-- About Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-5 align-items-end">
                <div class="col-lg-3 col-md-5 wow fadeInUp" data-wow-delay="0.1s">
                    <img class="img-fluid rounded" data-wow-delay="0.1s" src="{% static 'img/about.jpg' %}">
                </div>
                <div class="col-lg-6 col-md-7 wow fadeInUp" data-wow-delay="0.3s">
                    <h1 class="display-1 text-primary mb-0">10</h1>
                    <p class="text-primary mb-4">İllik Təcrübə</p>
                    <h1 class="display-5 mb-4">Torpaqsız kənd təsərrüfatında uğura əldə etmək üçün</h1>
                    <p class="mb-4">Azərbaycanın Peşəkar Hidroponik Su Mədəniyyəti NFT Kahı İstehsal Sisteminin Quraşdırılması və Məsləhətçi Şirkəti olaraq, Beynəlxalq Təcrübəmizi və Mühəndisliyimizi Birləşdirərək, İstixana və Torpaqsız Kənd Təsərrüfatı Sistemləri ilə Kənd Təsərrüfatının Gələcəyinə Sizinlə Öncülük edirik.</p>
                    <p class="mb-4">– OZ Kənd Təsərrüfatı və İstixana İdxal İxrac Ticarət Məhdud Cəmiyyəti; Müasir İstixana və Torpaqsız Kənd Təsərrüfatı Sistemləri sektorunda 10 illik təcrübəsi ilə yüksək keyfiyyətli istixana və torpaqsız kənd təsərrüfatı materialları ilə beynəlxalq açar təslim quraşdırma və məsləhət xidmətləri göstərir.</p>
                    <p class="mb-4">– Şirkətimizin baş ofisi Türkiyədə yerləşir, Azərbaycanda və qonşu ölkələrdə bütün iqlim xüsusiyyətlərinə xüsusi həllər təklif edərək peşəkar xidmət göstərir.</p>
                    <p class="mb-4">– Təcrübəli və peşəkar komandamızla layihənin hazırlanmasından istixana təhvil verilməsinə qədər hər mərhələdə tam nizam-intizamla işləyir, dəyərli müştərilərimizə xidmət göstəririk. Satış sonrası xidmət və texniki dəstək ilə həyata keçirdiyimiz hər bir layihədə sizə dəstək olur və müştəri məmnuniyyəti əsasında işimizi davam etdiririk.</p>
                    <p class="mb-4">Beynəlxalq Xidmət</p>
                    <p class="mb-4">Biz dünya standartlarında yüksək keyfiyyətli istixana materialları və torpaqsız kənd təsərrüfatı materialları ilə bütün dünyada istehsal, quraşdırma və məsləhət xidmətləri göstəririk.</p>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Oz Green House {% block title %}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600;700&family=Open+Sans:wght@400;500&display=swap" rel="stylesheet">  

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" role="status" style="width: 3rem; height: 3rem;"></div>
    </div>
    <!-- Spinner End -->


    <!-- Topbar Start -->
    <div class="container-fluid bg-dark text-light px-0 py-2">
        <div class="row gx-0 d-none d-lg-flex">
            <div class="col-lg-7 px-5 text-start">
                <div class="h-100 d-inline-flex align-items-center me-4">
                    <span class="fa fa-phone-alt me-2"></span>
                    <span>+994 993 14 16 18</span>
                </div>
                <div class="h-100 d-inline-flex align-items-center me-4">
                    <span class="far fa-envelope me-2"></span>
                    <span>info@ozgreenhouse.az</span>
                </div>
                <div class="h-100 d-inline-flex align-items-center">
                    <span class="far fa-envelope me-2"></span>
                    <span>ozgreenhouse@gmail.com</span>
                </div>
            </div>
            <div class="col-lg-5 px-5 text-end">
                <div class="h-100 d-inline-flex align-items-center mx-n2">
                    <span>Bizi izləyin:</span>
                    <a class="btn btn-link text-light" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-link text-light" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-link text-light" href=""><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-link text-light" href=""><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top p-0">
        <a href="{% url 'main:index' %}" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h1 class="m-0">Oz Green House</h1>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a href="{% url 'main:index' %}" class="nav-item nav-link {% if request.resolver_match.url_name == 'index' %} active {% endif %}">Əsas səhifə</a>
                <a href="{% url 'main:about' %}" class="nav-item nav-link {% if request.resolver_match.url_name == 'about' %} active {% endif %}">Bizim haqqımızda</a>
                <a href="{% url 'main:services' %}" class="nav-item nav-link {% if request.resolver_match.url_name == 'services' %} active {% endif %}">Xidmətlər</a>
                <a href="{% url 'main:projects' %}" class="nav-item nav-link {% if request.resolver_match.url_name == 'projects' %} active {% endif %}">Layihələr</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle {% if request.resolver_match.url_name == 'news' or request.resolver_match.url_name == 'faq' or request.resolver_match.url_name == 'products' %} active {% endif %}" data-bs-toggle="dropdown">Digər səhifələr</a>
                    <div class="dropdown-menu bg-light m-0">
                        <a href="{% url 'main:news' %}" class="dropdown-item  {% if request.resolver_match.url_name == 'news' %} active {% endif %}">Xəbərlər</a>
                        <a href="{% url 'main:faq' %}" class="dropdown-item {% if request.resolver_match.url_name == 'faq' %} active {% endif %}">Tez-tez soruşulan suallar</a> 
                        <a href="{% url 'main:products' %}" class="dropdown-item  {% if request.resolver_match.url_name == 'products' %} active {% endif %}">Məhsullar</a>
                        
                    </div>
                </div>
                <a href="{% url 'main:contact' %}" class="nav-item nav-link  {% if request.resolver_match.url_name == 'contact' %} active {% endif %}">Əlaqə</a>
            </div>
            <a href="{% url 'main:offer' %}" class="btn btn-primary py-4 px-lg-4 rounded-0 d-none d-lg-block">Təklif al<i class="fa fa-arrow-right ms-3"></i></a>
        </div>
    </nav>
    <!-- Navbar End -->

{% block content %}

{% endblock content %}

    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer mt-5 py-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-4">Bizim Ofisimiz</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Bakı, Azərbaycan</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+994 993 14 16 18</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@ozgreenhouse.az</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-square btn-outline-light rounded-circle me-2" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-square btn-outline-light rounded-circle me-2" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-square btn-outline-light rounded-circle me-2" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-square btn-outline-light rounded-circle me-2" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-4">İstixanaların istehsalı və quraşdırılması</h4>
                    <a class="btn btn-link" href="">Torpaqsız Kənd Təsərrüfatı Hidroponik Sistemləri</a>
                    <a class="btn btn-link" href="">Torpaqsız Kənd Təsərrüfatı Çiyələk Substratı Cocopeat Sistemi</a>
                    <a class="btn btn-link" href="">Beynəlxalq Konsaltinq Xidməti</a>
                    <a class="btn btn-link" href="">Günəş enerjisi</a>
                    <a class="btn btn-link" href="">Şitil və Toxum təminatı</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-4">Keçidlər</h4>
                    <a class="btn btn-link" href="{% url 'main:about' %}">Bizim haqqımızda</a>
                    <a class="btn btn-link" href="{% url 'main:contact' %}">Əlaqə</a>
                    <a class="btn btn-link" href="{% url 'main:services' %}"> Xidmətlər</a>
                    <a class="btn btn-link" href="{% url 'main:faq' %}">Tez-tez soruşulan suallar</a>
                    <a class="btn btn-link" href="{% url 'main:offer' %}">Təklif al</a>
                </div>
                
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Copyright Start -->
    <div class="container-fluid copyright py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="#">Öz Green House</a>, Bütün hüquqlar qorunur.
                </div>
            </div>
        </div>
    </div>
    <!-- Copyright End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/parallax/parallax.min.js' %}"></script>
    <script src="{% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Page Header Start -->
    <div class="container-fluid page-header py-5 mb-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container text-center py-5">
            <h1 class="display-3 text-white mb-4 animated slideInDown">Əlaqə</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a href="#">Əsas səhifə</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Əlaqə</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->
    
    <!-- Contact Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                    <p class="fs-5 fw-bold text-primary">Bizimlə əlaqə saxlayın.</p>
                    <h1 class="display-5 mb-5">Hər hansı bir sualınız varsa, bizimlə əlaqə saxlayın</h1>
                    <form>
                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="name" placeholder="Your Name">
                                    <label for="name">Adınız</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="email" class="form-control" id="email" placeholder="Your Email">
                                    <label for="email">E-mail</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="subject" placeholder="Subject">
                                    <label for="subject">Mövzu</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <textarea class="form-control" placeholder="Leave a message here" id="message" style="height: 100px"></textarea>
                                    <label for="message">Mesaj</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-primary py-3 px-4" type="submit">Mesaj Göndər</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s" style="min-height: 450px;">
                    <div class="position-relative rounded overflow-hidden h-100">
                        <iframe class="position-relative w-100 h-100"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                        frameborder="0" style="min-height: 450px; border:0;" allowfullscreen="" aria-hidden="false"
                        tabindex="0"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->
{% endblock content %}

templates/faq.html
{% extends 'base.html' %}

{% block content %}
    <!-- Page Header Start -->
    <div class="container-fluid page-header py-5 mb-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container text-center py-5">
            <h1 class="display-3 text-white mb-4 animated slideInDown">Tez-tez soruşulan suallar</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a href="#">Əsas səhifə</a></li>
                    <li class="breadcrumb-item"><a href="#">Digər səhifələr</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Tez-tez soruşulan suallar</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->

    <!-- Testimonial Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-5 wow fadeInUp" data-wow-delay="0.1s">
                    <p class="fs-5 fw-bold text-primary"></p>
                    <p class="fs-5 fw-bold text-primary">Torpaqsız Kənd Təsərrüfatı nədir?</p>
                    <p class="mb-4">Torpaqla heç bir təmas etmədən və torpaqdan başqa düzgün materiallardan istifadə etməklə bitki becərmə mühitini hazırlamağa və nəzarətli istehsal həyata keçirməyə imkan verən müasir kənd təsərrüfatı istehsal üsuludur.</p>
                   
                    <p class="fs-5 fw-bold text-primary">Niyə torpaqsız əkinçilik aparılmalıdır?</p>
                    <p class="mb-4">»Vahid sahəyə daha çox məhsul</p>
                    <p class="mb-4">»Torpaqla təması olmadığı üçün zərərvericilərdən uzaqdır </p>
                    <p class="mb-4">»Erkən məhsul yığa bilmək </p>
                    <p class="mb-4">»İlin 4 Fəsli məhsul yığımı </p>
                    <p class="mb-4">»Bitki məhsuldarlığının artması </p>
                    <p class="mb-4">»90%-ə qədər az və daha səmərəli su istifadəsi </p>

                    <p class="fs-5 fw-bold text-primary">1000 m² Hidroponik NFT Sistemində İstehsal Gücü nə qədərdir?</p>
                    <p class="mb-4">Məhsullardan asılı olaraq dəyişsə də, Torpaqsız Kənd Təsərrüfatı su mədəniyyəti NFT sistemlərində, yəni üfüqi düz istehsal sistemlərində</p>
                    <p class="mb-4">»Kahı tipli məhsullar üçün orta hesabla 13.000 – 14.000 ədəd </p>
                    <p class="mb-4">»Reyhan kimi aromatik bitkilər üçün orta hesabla 25.000 - 30.000 ədəd </p>
                    <p class="mb-4">»Ümumi tutumumuz 1000 m² dir. </p>

                    <p class="fs-5 fw-bold text-primary">Torpaqsız əkinçiliklə tarla istehsalı arasındakı fərq nədir?</p>
                    <p class="mb-4">Məhsullardan asılı olaraq dəyişsə də, tarla istehsalı ilə torpaqsız kənd təsərrüfatı istehsalı arasında məhsul istehsal gücündə orta hesabla 2-4 dəfə fərq var. 
                        Məsələn, tarla şəraitində 1000 m²-ə orta hesabla 6500-7500 ədəd kahı əkmək mümkün olduğu halda, torpaqsız kənd təsərrüfatında bu rəqəm 14000-dir. Göründüyü kimi, istehsal gücündə 2 dəfə fərq var.</p>
                        
                    <p class="mb-4">Lakin ən mühüm tərəfi odur ki, tarla istehsalı üçün mövsüm orta hesabla ildə iki dəfə əkin və məhsul yığımı ilə başa çatır. Torpaqsız kənd təsərrüfatında biz ildə cəmi 7-8 dəfə məhsul veririk, yəni bu ümumi gücü bütün il boyu davamlı şəkildə istehsal edə bilərik.</p>
                  
                    <p class="fs-5 fw-bold text-primary">Torpaqsız əkinçilik üçün istifadə olunan gübrə məhlulları və pestisidlər tarla istehsalı ilə müqayisədə zərərlidirmi?</p>
                    <p class="mb-4">Torpaqsız əkinçilikdə istifadə edilən gübrə məhlulları normal torpaq əkinçiliyində istifadə olunan tamamilə standart gübrələrdir. Lakin bu gübrələr müəyyən nisbətlərdə qarışdırılır və bitkiyə lazım olan miqdarda verilir. Torpaqsız əkinçilikdə istehsal etdiyimiz bitkilər üçün müxtəlif qarışıq formulaları mövcuddur. Bu qarışıqlarla bitkilər ehtiyac duyduqları qədər bitki qida maddələrini əldə edə və beləliklə daha sağlam böyüyə bilərlər.</p>

                    <p class="mb-4">Pestisidlərə gəlincə, torpaqsız əkinçilikdə torpaqla təmasda olmadığımız üçün torpaqdan gələ biləcək xəstəlik və zərərvericilərdən uzaq olduğumuz üçün bitkilərimizə xəstəlik və zərərvericilər gəlmir. Bu səbəbdən ətraf mühitin steril olmasını təmin etmək üçün pestisidlərdən istifadə etmirik. Bu lazım deyil. Tamamilə dərmansız və bitkinin böyüməsi üçün lazım olan qida mühitində böyüyən bitkilər stress keçirmir və daha keyfiyyətli, daha sağlam və organik qida əldə edirik.</p>
                    
                    <p class="fs-5 fw-bold text-primary">Qidalandırıcı məhlullar necə alınır?</p>
                    <p class="mb-4">Sizi, dəyərli obyekt sahiblərimizi və torpaqsız kənd təsərrüfatı istehsalçılarını hər aspektdə, eləcə də Torpaqsız Kənd Təsərrüfatı Qidalandırıcı Həllərində hər zaman dəstəkləyirik.</p>
                    <p class="mb-4">Peşəkar mühəndislərimizlə hər zaman yanınızdayıq.</p>

                    <p class="fs-5 fw-bold text-primary">Torpaqsız əkinçilik sistemləri üçün avtomatlaşdırma lazımdırmı?</p>
                    <p class="mb-4">Avtomatlaşdırma sistemi, Torpaqsız əkinçilik üçün ilk ehtiyacımız olan gübrə məhlullarının və pH balanslaşdırıcısının avtomatik olaraq istifadə olunacaq su çəninə qidalanaraq sistemə göndərilməsini təmin edir. Torpaqsız kənd təsərrüfatı və akvakultura üçün lazımi vaxtda dozajı dəqiq ölçmələrlə həyata keçirən avtomatlaşdırma sistemi zəruridir. Bu zaman sistemə düzgün təmin etdiyimiz su sayəsində bitki istehsalında yarana biləcək problemlər minimuma endirilir.</p>
                    
                    <p class="fs-5 fw-bold text-primary">Torpaqsız Kənd Təsərrüfatı İstixana Quraşdırma Xərcləri?</p>
                    <p class="mb-4">Quraşdırma xərcləri istixana dizaynına, ümumi ölçüsünə və bir çox parametrlərə görə dəyişir.</p>

                    <p class="mb-4">Zəhmət olmasa, e-poçt göndərməklə və ya bizə zəng etməklə komandamızdan əraziniz üçün təklif tələb edin.</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Testimonial End -->

{% endblock content %}

templates/news.html
{% extends 'base.html' %}

{% block content %}
    <!-- Page Header Start -->
    <div class="container-fluid page-header py-5 mb-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container text-center py-5">
            <h1 class="display-3 text-white mb-4 animated slideInDown">Xəbərlər</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a href="#">Əsas səhifə</a></li>
                    <li class="breadcrumb-item"><a href="#">Digər səhifələr</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Xəbərlər</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->

{% endblock content %}

templates/products.html
{% extends 'base.html' %}

{% block content %}
    <!-- Page Header Start -->
    <div class="container-fluid page-header py-5 mb-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container text-center py-5">
            <h1 class="display-3 text-white mb-4 animated slideInDown">Məhsullar</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a href="#">Əsas səhifə</a></li>
                    <li class="breadcrumb-item"><a href="#">Digər səhifələr</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Məhsullar</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->
{% endblock content %}